<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__product3_quantity</name>
   <tag></tag>
   <elementGuidId>71b89f33-eb78-4128-9d6c-1a610b560db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;product3_quantity&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='product3_quantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73d631f4-6772-4b6b-961d-8c275fe4cbe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product3_quantity</value>
      <webElementGuid>33fb467c-5d9e-49fd-9ea8-96d9257cbf61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff080453-a720-4a01-ab92-686a27a9803f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>660d275f-9103-4e04-b2d1-bdc6807f56dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>d143ba6f-297e-4816-a951-6b2c7c3b84e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hTZgZg bTLpdi</value>
      <webElementGuid>c39144f9-57c3-4ca1-8407-cd2c05723318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>3eac0449-2edd-450e-ba9f-6f5f203db79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-iqHYmW sc-iJuVqt jeNtcR hKpvaj&quot;]/div[@class=&quot;sc-jJEKmz jGmrOZ product-list-wrapper&quot;]/div[@class=&quot;product-image-placeholder&quot;]/div[@class=&quot;sc-gWHigU kDjMZY product-content-wrapper&quot;]/div[@class=&quot;sc-cBNeex hZmilT product-content&quot;]/div[@class=&quot;sc-citxvW bfngsU product-block-wrapper&quot;]/div[@class=&quot;product-block&quot;]/div[@class=&quot;product-row controls&quot;]/div[@class=&quot;quantity&quot;]/div[@class=&quot;sc-gTgzoy iryiFk&quot;]/input[@class=&quot;sc-hTZgZg bTLpdi&quot;]</value>
      <webElementGuid>886eed01-43d7-445b-836c-2e526d9c134d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='product3_quantity']</value>
      <webElementGuid>f3c8c57b-58e6-48dd-8d92-db28b3ca08cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div[3]/div[3]/div[2]/div/input</value>
      <webElementGuid>4cc4af4d-51fc-468c-ab72-3358fb96d9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/div/input</value>
      <webElementGuid>b077f206-5ec9-4a9e-a5bb-148413474f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'product3_quantity' and @type = 'text']</value>
      <webElementGuid>14837797-5cd8-4b28-8cf3-272ed06453fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
