<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__product1_quantity</name>
   <tag></tag>
   <elementGuidId>6493b4b8-c57c-4e53-bbbd-f23d2884a919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;product1_quantity&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='product1_quantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0847731-fb7c-4723-a98b-14bce52a5cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product1_quantity</value>
      <webElementGuid>0711e03b-624b-4077-9344-bdd5f8a99026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ccbe849-12a0-4478-8dee-8fafb57f2d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>e02d9f02-51cc-4c50-b151-373cff28af75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>9c9fc654-45d7-43ec-9258-45319c11859a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hTZgZg bTLpdi</value>
      <webElementGuid>9c268d25-fdb5-43f5-ba8d-f6b051c06145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>5f7cee99-082a-4a58-ae97-289204d330c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-iqHYmW sc-iJuVqt jeNtcR hKpvaj&quot;]/div[@class=&quot;sc-jJEKmz jGmrOZ product-list-wrapper&quot;]/div[@class=&quot;product-image-placeholder&quot;]/div[@class=&quot;sc-gWHigU kDjMZY product-content-wrapper&quot;]/div[@class=&quot;sc-cBNeex hZmilT product-content&quot;]/div[@class=&quot;sc-citxvW bfngsU product-block-wrapper&quot;]/div[@class=&quot;product-block&quot;]/div[@class=&quot;product-row controls&quot;]/div[@class=&quot;quantity&quot;]/div[@class=&quot;sc-gTgzoy iryiFk&quot;]/input[@class=&quot;sc-hTZgZg bTLpdi&quot;]</value>
      <webElementGuid>dd8f13f1-b5dc-4d10-bba6-f200e90ebc93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='product1_quantity']</value>
      <webElementGuid>06ab5712-980c-43ce-a477-186db1e745a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div/div[3]/div[2]/div/input</value>
      <webElementGuid>850ad4f1-4594-4812-9f47-a6d81fe73763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>618545c8-2dbb-4763-a3b9-6c5349684906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'product1_quantity' and @type = 'text']</value>
      <webElementGuid>8d09bc75-65f9-443e-b7a2-1027b6c0c2af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
