<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__product2_quantity</name>
   <tag></tag>
   <elementGuidId>724cb0c3-ce47-4e07-b854-32a3325161ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;product2_quantity&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='product2_quantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e1951a4-ce1b-4fc9-81f2-6ad4bd6e7193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product2_quantity</value>
      <webElementGuid>a2c05c3b-b35f-45ec-be67-4d022d00b8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f99bc4bd-3480-4de7-9a8d-3196ae3b48c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>f92fc50a-0d89-4540-9db5-b0b530fd49de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>3c4dc7e4-cf41-4a99-8caf-6edba8dd061c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hTZgZg bTLpdi</value>
      <webElementGuid>6d667e91-79eb-4196-9078-2d11ee1f3294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>d2b61606-4d9f-4e81-bfa3-f2b07c573bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-iqHYmW sc-iJuVqt jeNtcR hKpvaj&quot;]/div[@class=&quot;sc-jJEKmz jGmrOZ product-list-wrapper&quot;]/div[@class=&quot;product-image-placeholder&quot;]/div[@class=&quot;sc-gWHigU kDjMZY product-content-wrapper&quot;]/div[@class=&quot;sc-cBNeex hZmilT product-content&quot;]/div[@class=&quot;sc-citxvW bfngsU product-block-wrapper&quot;]/div[@class=&quot;product-block&quot;]/div[@class=&quot;product-row controls&quot;]/div[@class=&quot;quantity&quot;]/div[@class=&quot;sc-gTgzoy iryiFk&quot;]/input[@class=&quot;sc-hTZgZg bTLpdi&quot;]</value>
      <webElementGuid>31ea7d5f-a5d8-4588-a619-612e0583a2be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='product2_quantity']</value>
      <webElementGuid>72063f39-1d1e-429a-8e61-0817cdd3b493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div[2]/div[3]/div[2]/div/input</value>
      <webElementGuid>dc113d9c-1148-4337-a12c-bc129fbde2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div/input</value>
      <webElementGuid>50fd2c09-8060-4721-932a-ceed77ecc4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'product2_quantity' and @type = 'text']</value>
      <webElementGuid>7e80ee99-df97-4872-bf11-54b002a65c7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
