<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>f07158eb-07a5-4ea0-b948-e37ecc3c34ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#credify-scrollable-content > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='credify-scrollable-content']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d2d1a9e-7095-435e-b681-73c60db3525e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credify-scrollable-content&quot;)/div[1]</value>
      <webElementGuid>7d8883fb-84ca-4c99-a051-31b960babce1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div</value>
      <webElementGuid>a77cbece-0f4a-444e-b65c-b80266f54f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>bd60a020-cf30-4f24-b490-b384395bb220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
