<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Verify your identity</name>
   <tag></tag>
   <elementGuidId>b5e890a2-9e62-4e3a-be56-d6b4c8c09e9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-ckTSus.ScjFp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='credify-passport-body']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>36339b24-e589-4efc-90b8-1ffd18bcf10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ckTSus ScjFp</value>
      <webElementGuid>3dfa20b6-dc97-4f89-a3df-a797ee049b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify your identity</value>
      <webElementGuid>254b02bf-bf24-40e2-afcb-7787fb4d2e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credify-passport-body&quot;)/div[@class=&quot;sc-ckTSus ScjFp&quot;]</value>
      <webElementGuid>5b6772b8-6b59-4609-9575-dcfad117cf8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-passport-body']/div</value>
      <webElementGuid>ea41a42f-b02f-43de-af40-441c7ffe733d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>261d40e8-2865-43de-880f-624829d630ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Verify your identity' or . = 'Verify your identity')]</value>
      <webElementGuid>61dcbcd1-1de9-44f3-8710-2bab2ca37322</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
