<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please provide the following informatio_4b0fdc</name>
   <tag></tag>
   <elementGuidId>9f1f0cf3-ef3f-4d31-aacf-cfff7d44153f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#credify-scrollable-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='credify-scrollable-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>673f8c80-a798-4faf-b86a-9b22265f4960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>credify-scrollable-content</value>
      <webElementGuid>5ad63880-c5d6-4830-9295-c77d5ea1daf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fXazdy UjHkE</value>
      <webElementGuid>4c2773f9-beb6-4e4a-865d-2c93f4ef9ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please provide the following information in order to complete the application.Information provided by BNPL consumerBNPL provider 1 will securely receive these bits of information from BNPL consumerPhone numberIdentity informationInformation provided by yourselfBasic profileFull nameDate of birthGenderMaleFemaleID numberEmail addressVERIFIED Province/CityBà Rịa - Vũng TàuDistrictCôn ĐảoStreetYour applicationHousing typeParent's housePrivate houseParent's houseRentInstallment purchaseOtherEducation levelPost-gradIntermediate schoolSecondary schoolHigh schoolCollegeUniversityGraduate schoolPost-gradDoctor of PhilosophyThông tin công tyCompany IndustryReal estateServiceFinance/InsuranceReal estatePharmaceuticalAgricultureTransportGovernmentRetailConstructionEducationHealth careHigh techEntertainmentNewsEnergyMiningOtherCompany Registration typeHousehold businessJointLimitedStateForeignHousehold businessCooperativeTax numberDepartmentLabor contract typeContributorContributorProbationary1 yearOver 1 yearIndefinite termThông tin nhân viênOccupationFiremanPoliceFiremanWorking positionHead of departmentEmployeeSpecialistHead of unitHead of departmentGeneral directorCountryViệt NamProvince/CityBắc KạnDistrictBạch ThôngWard/Commune/TownCao SơnVillage/Hamlet/Residential groupAddressStreetStreet numberMarital statusDivorcedSingleMarriedSeparatedDivorcedWidowOtherMonthly family income2,000,000đ2,000,000đ20,000,000đ200,000,000đMonthly wage income2,000,000đ2,000,000đ20,000,000đ200,000,000đPrimary reference personFull namePhone numberRelationshipSpouseSpouseParentChildSiblingCousinColleagueNeighborFriendSecondary reference personFull namePhone numberRelationshipColleagueSpouseParentChildSiblingCousinColleagueNeighborFriendThông tin What is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with BNPL provider 1 for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.</value>
      <webElementGuid>2a7d6167-f07e-4313-9c32-0481b83ff413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credify-scrollable-content&quot;)</value>
      <webElementGuid>d9fae147-c66b-4a79-973a-93a16a30cb87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']</value>
      <webElementGuid>8850d6a4-2c0a-488b-bbae-1bfe29efe3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-passport-body']/div[3]/div</value>
      <webElementGuid>c9e8347b-1ece-4163-aaa9-8bfb9aa48deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[1]/following::div[5]</value>
      <webElementGuid>c3a88e4c-bc87-4c26-a98f-099f4bfa37cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div</value>
      <webElementGuid>56ded7b4-d131-4e4a-ba7e-31f54ed77f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'credify-scrollable-content' and (text() = concat(&quot;Please provide the following information in order to complete the application.Information provided by BNPL consumerBNPL provider 1 will securely receive these bits of information from BNPL consumerPhone numberIdentity informationInformation provided by yourselfBasic profileFull nameDate of birthGenderMaleFemaleID numberEmail addressVERIFIED Province/CityBà Rịa - Vũng TàuDistrictCôn ĐảoStreetYour applicationHousing typeParent&quot; , &quot;'&quot; , &quot;s housePrivate houseParent&quot; , &quot;'&quot; , &quot;s houseRentInstallment purchaseOtherEducation levelPost-gradIntermediate schoolSecondary schoolHigh schoolCollegeUniversityGraduate schoolPost-gradDoctor of PhilosophyThông tin công tyCompany IndustryReal estateServiceFinance/InsuranceReal estatePharmaceuticalAgricultureTransportGovernmentRetailConstructionEducationHealth careHigh techEntertainmentNewsEnergyMiningOtherCompany Registration typeHousehold businessJointLimitedStateForeignHousehold businessCooperativeTax numberDepartmentLabor contract typeContributorContributorProbationary1 yearOver 1 yearIndefinite termThông tin nhân viênOccupationFiremanPoliceFiremanWorking positionHead of departmentEmployeeSpecialistHead of unitHead of departmentGeneral directorCountryViệt NamProvince/CityBắc KạnDistrictBạch ThôngWard/Commune/TownCao SơnVillage/Hamlet/Residential groupAddressStreetStreet numberMarital statusDivorcedSingleMarriedSeparatedDivorcedWidowOtherMonthly family income2,000,000đ2,000,000đ20,000,000đ200,000,000đMonthly wage income2,000,000đ2,000,000đ20,000,000đ200,000,000đPrimary reference personFull namePhone numberRelationshipSpouseSpouseParentChildSiblingCousinColleagueNeighborFriendSecondary reference personFull namePhone numberRelationshipColleagueSpouseParentChildSiblingCousinColleagueNeighborFriendThông tin What is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with BNPL provider 1 for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.&quot;) or . = concat(&quot;Please provide the following information in order to complete the application.Information provided by BNPL consumerBNPL provider 1 will securely receive these bits of information from BNPL consumerPhone numberIdentity informationInformation provided by yourselfBasic profileFull nameDate of birthGenderMaleFemaleID numberEmail addressVERIFIED Province/CityBà Rịa - Vũng TàuDistrictCôn ĐảoStreetYour applicationHousing typeParent&quot; , &quot;'&quot; , &quot;s housePrivate houseParent&quot; , &quot;'&quot; , &quot;s houseRentInstallment purchaseOtherEducation levelPost-gradIntermediate schoolSecondary schoolHigh schoolCollegeUniversityGraduate schoolPost-gradDoctor of PhilosophyThông tin công tyCompany IndustryReal estateServiceFinance/InsuranceReal estatePharmaceuticalAgricultureTransportGovernmentRetailConstructionEducationHealth careHigh techEntertainmentNewsEnergyMiningOtherCompany Registration typeHousehold businessJointLimitedStateForeignHousehold businessCooperativeTax numberDepartmentLabor contract typeContributorContributorProbationary1 yearOver 1 yearIndefinite termThông tin nhân viênOccupationFiremanPoliceFiremanWorking positionHead of departmentEmployeeSpecialistHead of unitHead of departmentGeneral directorCountryViệt NamProvince/CityBắc KạnDistrictBạch ThôngWard/Commune/TownCao SơnVillage/Hamlet/Residential groupAddressStreetStreet numberMarital statusDivorcedSingleMarriedSeparatedDivorcedWidowOtherMonthly family income2,000,000đ2,000,000đ20,000,000đ200,000,000đMonthly wage income2,000,000đ2,000,000đ20,000,000đ200,000,000đPrimary reference personFull namePhone numberRelationshipSpouseSpouseParentChildSiblingCousinColleagueNeighborFriendSecondary reference personFull namePhone numberRelationshipColleagueSpouseParentChildSiblingCousinColleagueNeighborFriendThông tin What is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with BNPL provider 1 for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.&quot;))]</value>
      <webElementGuid>39e0f092-a5e9-4e4c-922a-291e36b6b337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
