<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hi PhngHu GiangH Ch MinhHa BnhHng YnKhn_4c5cd7</name>
   <tag></tag>
   <elementGuidId>d853edf6-cb0f-45a3-bfcf-90e5c85227e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='----item-id----employment.claims.company_address.claims.region']/div[2]/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c2463ce-1b66-44ed-895f-7920e05e9661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-virtual-list</value>
      <webElementGuid>22ab8b15-e0c5-4c77-a51a-331a22c0303d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hải PhòngHậu GiangHồ Chí MinhHòa BìnhHưng YênKhánh HòaKiên GiangKon TumLai ChâuLâm Đồng</value>
      <webElementGuid>c3d1da50-7229-4d86-a605-c35988de65a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;----item-id----employment.claims.company_address.claims.region&quot;)/div[2]/div[1]/div[@class=&quot;ant-select-dropdown ant-select-dropdown-placement-bottomRight&quot;]/div[1]/div[@class=&quot;rc-virtual-list&quot;]</value>
      <webElementGuid>d22a19c2-7c56-4c3c-a7eb-4dbb483ed79d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='----item-id----employment.claims.company_address.claims.region']/div[2]/div/div/div/div[2]</value>
      <webElementGuid>0a18d21c-14bb-4947-8b8d-6946def63be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[1]/following::div[9]</value>
      <webElementGuid>60c2ef5d-ae77-4991-83a0-dc7c9f516a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province/City'])[2]/following::div[15]</value>
      <webElementGuid>e4f38b2a-db7c-4432-bb5d-26d3f47d5f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>01f84107-699a-4be2-aea3-93359af92fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hải PhòngHậu GiangHồ Chí MinhHòa BìnhHưng YênKhánh HòaKiên GiangKon TumLai ChâuLâm Đồng' or . = 'Hải PhòngHậu GiangHồ Chí MinhHòa BìnhHưng YênKhánh HòaKiên GiangKon TumLai ChâuLâm Đồng')]</value>
      <webElementGuid>24748127-ac62-4ea0-9cf7-14aaee95ff17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
