<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2,000,000</name>
   <tag></tag>
   <elementGuidId>481ec140-e38d-4866-9348-36026cb323da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='2,000,000']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>45a79611-e207-4746-b08d-b7601f10281d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>9aaf1345-e894-4ba7-bd93-d359faeac282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2,000,000đ</value>
      <webElementGuid>0a0519d3-5b04-4629-b9df-61f7dcb2748f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2,000,000&quot;)/div[@class=&quot;ant-select-item-option-content&quot;]</value>
      <webElementGuid>83dfb8fe-83c4-420c-9d3d-17d43afec2af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2,000,000']/div</value>
      <webElementGuid>37edc9c3-6488-4c36-a0e8-9c07c7df4374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly wage income'])[1]/following::div[19]</value>
      <webElementGuid>b1f08d5a-e5da-4a43-b871-38978d4a91d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Income &amp; dependent person'])[1]/following::div[22]</value>
      <webElementGuid>96db7af6-7a29-42b4-abce-2fe59d00c0ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of dependent person'])[1]/preceding::div[10]</value>
      <webElementGuid>1718fca9-d5eb-4369-b67d-2189d98f0c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::div[11]</value>
      <webElementGuid>c5b96128-2b73-468e-8f89-aa0d35398e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>93dd30b9-aab7-4b7c-863e-4e5bd04fc2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2,000,000đ' or . = '2,000,000đ')]</value>
      <webElementGuid>fcf3028b-4031-4f8e-b193-34d9abd443dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
