<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please provide the following informatio_4b0fdc_1_2</name>
   <tag></tag>
   <elementGuidId>7991018a-a14a-41db-9ec9-b47965fdfd31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#credify-scrollable-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='credify-scrollable-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f779a36-9feb-422a-927c-e6c5c6fb14b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>credify-scrollable-content</value>
      <webElementGuid>daac6cd1-fa20-4b2f-aba4-5f24ce2db9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fXazdy UjHkE</value>
      <webElementGuid>5dfca8b1-c95e-4c74-8979-f3262615df90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please provide the following information in order to complete the application.Information provided by BNPL consumerBNPL provider 1 will securely receive these bits of information from BNPL consumerPhone numberIdentity informationInformation provided by yourselfBasic profileFull nameDate of birthGenderMaleFemaleID numberEmail addressVERIFYEmail is not verifiedProvince/CityBà Rịa - Vũng TàuDistrictBà RịaStreetYour applicationHousing typePrivate housePrivate houseParent's houseRentInstallment purchaseOtherEducation levelSecondary schoolIntermediate schoolSecondary schoolHigh schoolCollegeUniversityGraduate schoolPost-gradDoctor of PhilosophyThông tin công tyCompany IndustryFinance/InsuranceServiceFinance/InsuranceReal estatePharmaceuticalAgricultureTransportGovernmentRetailConstructionEducationHealth careHigh techEntertainmentNewsEnergyMiningOtherCompany Registration typeForeignJointLimitedStateForeignHousehold businessCooperativeTax numberDepartmentLabor contract typeProbationaryContributorProbationary1 yearOver 1 yearIndefinite termThông tin nhân viênOccupationPolicePoliceFiremanWorking positionHead of departmentEmployeeSpecialistHead of unitHead of departmentGeneral directorCountryViệt NamProvince/CityBắc GiangDistrictTân YênWard/Commune/TownCao ThượngVillage/Hamlet/Residential groupAddressStreetStreet numberMarital statusSeparatedSingleMarriedSeparatedDivorcedWidowOtherMonthly family income2,000,000đ2,000,000đ20,000,000đ200,000,000đMonthly wage income2,000,000đ2,000,000đ20,000,000đ200,000,000đPrimary reference personFull namePhone numberRelationshipNeighborSpouseParentChildSiblingCousinColleagueNeighborFriendSecondary reference personFull namePhone numberRelationshipNeighborSpouseParentChildSiblingCousinColleagueNeighborFriendThông tin What is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with BNPL provider 1 for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.</value>
      <webElementGuid>5b9623d3-d036-4ab0-8a70-064f9197a155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credify-scrollable-content&quot;)</value>
      <webElementGuid>028784b7-4b3f-4853-bd00-a7f207db5c75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']</value>
      <webElementGuid>fc517b1e-fa4d-490e-89f0-da0552c12c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-passport-body']/div[3]/div</value>
      <webElementGuid>0979edaf-7578-4370-82b5-c82085db0d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[1]/following::div[5]</value>
      <webElementGuid>a0a008b6-3a29-456f-a21f-35cb7d004e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div</value>
      <webElementGuid>cd269347-0977-4175-aa4a-7b058122ca8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'credify-scrollable-content' and (text() = concat(&quot;Please provide the following information in order to complete the application.Information provided by BNPL consumerBNPL provider 1 will securely receive these bits of information from BNPL consumerPhone numberIdentity informationInformation provided by yourselfBasic profileFull nameDate of birthGenderMaleFemaleID numberEmail addressVERIFYEmail is not verifiedProvince/CityBà Rịa - Vũng TàuDistrictBà RịaStreetYour applicationHousing typePrivate housePrivate houseParent&quot; , &quot;'&quot; , &quot;s houseRentInstallment purchaseOtherEducation levelSecondary schoolIntermediate schoolSecondary schoolHigh schoolCollegeUniversityGraduate schoolPost-gradDoctor of PhilosophyThông tin công tyCompany IndustryFinance/InsuranceServiceFinance/InsuranceReal estatePharmaceuticalAgricultureTransportGovernmentRetailConstructionEducationHealth careHigh techEntertainmentNewsEnergyMiningOtherCompany Registration typeForeignJointLimitedStateForeignHousehold businessCooperativeTax numberDepartmentLabor contract typeProbationaryContributorProbationary1 yearOver 1 yearIndefinite termThông tin nhân viênOccupationPolicePoliceFiremanWorking positionHead of departmentEmployeeSpecialistHead of unitHead of departmentGeneral directorCountryViệt NamProvince/CityBắc GiangDistrictTân YênWard/Commune/TownCao ThượngVillage/Hamlet/Residential groupAddressStreetStreet numberMarital statusSeparatedSingleMarriedSeparatedDivorcedWidowOtherMonthly family income2,000,000đ2,000,000đ20,000,000đ200,000,000đMonthly wage income2,000,000đ2,000,000đ20,000,000đ200,000,000đPrimary reference personFull namePhone numberRelationshipNeighborSpouseParentChildSiblingCousinColleagueNeighborFriendSecondary reference personFull namePhone numberRelationshipNeighborSpouseParentChildSiblingCousinColleagueNeighborFriendThông tin What is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with BNPL provider 1 for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.&quot;) or . = concat(&quot;Please provide the following information in order to complete the application.Information provided by BNPL consumerBNPL provider 1 will securely receive these bits of information from BNPL consumerPhone numberIdentity informationInformation provided by yourselfBasic profileFull nameDate of birthGenderMaleFemaleID numberEmail addressVERIFYEmail is not verifiedProvince/CityBà Rịa - Vũng TàuDistrictBà RịaStreetYour applicationHousing typePrivate housePrivate houseParent&quot; , &quot;'&quot; , &quot;s houseRentInstallment purchaseOtherEducation levelSecondary schoolIntermediate schoolSecondary schoolHigh schoolCollegeUniversityGraduate schoolPost-gradDoctor of PhilosophyThông tin công tyCompany IndustryFinance/InsuranceServiceFinance/InsuranceReal estatePharmaceuticalAgricultureTransportGovernmentRetailConstructionEducationHealth careHigh techEntertainmentNewsEnergyMiningOtherCompany Registration typeForeignJointLimitedStateForeignHousehold businessCooperativeTax numberDepartmentLabor contract typeProbationaryContributorProbationary1 yearOver 1 yearIndefinite termThông tin nhân viênOccupationPolicePoliceFiremanWorking positionHead of departmentEmployeeSpecialistHead of unitHead of departmentGeneral directorCountryViệt NamProvince/CityBắc GiangDistrictTân YênWard/Commune/TownCao ThượngVillage/Hamlet/Residential groupAddressStreetStreet numberMarital statusSeparatedSingleMarriedSeparatedDivorcedWidowOtherMonthly family income2,000,000đ2,000,000đ20,000,000đ200,000,000đMonthly wage income2,000,000đ2,000,000đ20,000,000đ200,000,000đPrimary reference personFull namePhone numberRelationshipNeighborSpouseParentChildSiblingCousinColleagueNeighborFriendSecondary reference personFull namePhone numberRelationshipNeighborSpouseParentChildSiblingCousinColleagueNeighborFriendThông tin What is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with BNPL provider 1 for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.&quot;))]</value>
      <webElementGuid>68c1c080-16cd-49f1-a1e2-86d7d68fa160</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
