<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please provide the following informatio_4b0fdc_1</name>
   <tag></tag>
   <elementGuidId>6c43fc60-c434-4268-b319-db371b310920</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#credify-scrollable-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='credify-scrollable-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>28ab7578-00f2-4c8b-9d0b-563229f44f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>credify-scrollable-content</value>
      <webElementGuid>31f2c82c-4b51-4545-9390-6f14879c06d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fXazdy UjHkE</value>
      <webElementGuid>55046139-45a2-46cf-b389-b61912a1b031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please provide the following information in order to complete the application.Information provided by BNPL consumerBNPL provider 1 will securely receive these bits of information from BNPL consumerPhone numberIdentity informationInformation provided by yourselfBasic profileFull nameDate of birthGenderMaleFemaleID numberEmail addressVERIFIED Province/CityBà Rịa - Vũng TàuBà Rịa - Vũng TàuDistrictStreetYour applicationHousing typeEducation levelThông tin công tyCompany IndustryCompany Registration typeTax numberDepartmentLabor contract typeThông tin nhân viênOccupationWorking positionCountryViệt NamProvince/CityDistrictWard/Commune/TownVillage/Hamlet/Residential groupAddressStreetStreet numberMarital statusMonthly family incomeMonthly wage incomePrimary reference personFull namePhone numberRelationshipSecondary reference personFull namePhone numberRelationshipThông tin What is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with BNPL provider 1 for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.</value>
      <webElementGuid>c5996863-543b-4848-a2fa-d315512d013a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credify-scrollable-content&quot;)</value>
      <webElementGuid>229a0a74-25e9-4461-8425-d9dd426b55e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']</value>
      <webElementGuid>1e3ccdb6-1a69-4c93-9002-c8d712bd447c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-passport-body']/div[3]/div</value>
      <webElementGuid>391435e5-4d8a-4ade-bed3-4b6756e01891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[1]/following::div[5]</value>
      <webElementGuid>89f45b2d-8191-4273-833e-7d5461f216f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div</value>
      <webElementGuid>156c44e9-f60b-48c2-b910-9a3b22f0ce1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'credify-scrollable-content' and (text() = 'Please provide the following information in order to complete the application.Information provided by BNPL consumerBNPL provider 1 will securely receive these bits of information from BNPL consumerPhone numberIdentity informationInformation provided by yourselfBasic profileFull nameDate of birthGenderMaleFemaleID numberEmail addressVERIFIED Province/CityBà Rịa - Vũng TàuBà Rịa - Vũng TàuDistrictStreetYour applicationHousing typeEducation levelThông tin công tyCompany IndustryCompany Registration typeTax numberDepartmentLabor contract typeThông tin nhân viênOccupationWorking positionCountryViệt NamProvince/CityDistrictWard/Commune/TownVillage/Hamlet/Residential groupAddressStreetStreet numberMarital statusMonthly family incomeMonthly wage incomePrimary reference personFull namePhone numberRelationshipSecondary reference personFull namePhone numberRelationshipThông tin What is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with BNPL provider 1 for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.' or . = 'Please provide the following information in order to complete the application.Information provided by BNPL consumerBNPL provider 1 will securely receive these bits of information from BNPL consumerPhone numberIdentity informationInformation provided by yourselfBasic profileFull nameDate of birthGenderMaleFemaleID numberEmail addressVERIFIED Province/CityBà Rịa - Vũng TàuBà Rịa - Vũng TàuDistrictStreetYour applicationHousing typeEducation levelThông tin công tyCompany IndustryCompany Registration typeTax numberDepartmentLabor contract typeThông tin nhân viênOccupationWorking positionCountryViệt NamProvince/CityDistrictWard/Commune/TownVillage/Hamlet/Residential groupAddressStreetStreet numberMarital statusMonthly family incomeMonthly wage incomePrimary reference personFull namePhone numberRelationshipSecondary reference personFull namePhone numberRelationshipThông tin What is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with BNPL provider 1 for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.')]</value>
      <webElementGuid>9794bb69-02a2-4927-b5bb-d5f129e00073</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
