<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WardCommuneTown_ant-select-selector</name>
   <tag></tag>
   <elementGuidId>4f694fca-0306-4c25-b82a-d78ecb092cb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-select.ant-select-borderless.sc-kLojOw.kprLit.ant-select-single.ant-select-show-arrow.ant-select-open.ant-select-show-search > div.ant-select-selector</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='credify-scrollable-content']/div/div/div[8]/form/div[2]/div[2]/div[10]/div/div[4]/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d12335a1-7a12-403b-87fc-2cb73431e26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selector</value>
      <webElementGuid>7afca8bc-6a2f-49b3-9483-e9c7fd35775d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credify-scrollable-content&quot;)/div[@class=&quot;sc-iJCRrE sc-giAqHp sc-cSiAOC bojiJp dHLXvA cBTyES&quot;]/div[@class=&quot;ant-col ant-col-24&quot;]/div[@class=&quot;sc-cjzNjn fKyDrK&quot;]/form[@class=&quot;ant-form ant-form-vertical&quot;]/div[@class=&quot;ant-col ant-col-24 appForm-group&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-24&quot;]/div[@class=&quot;ant-col ant-col-24 sc-iueNdr enpikb&quot;]/div[@class=&quot;ant-row ant-form-item Item-Style form--item-employment.claims.work_address.claims.sublocality ant-form-item-has-success&quot;]/div[@class=&quot;ant-col ant-col-24 ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;ant-select ant-select-borderless sc-kLojOw kprLit ant-select-single ant-select-show-arrow ant-select-open ant-select-show-search&quot;]/div[@class=&quot;ant-select-selector&quot;]</value>
      <webElementGuid>29af6875-eb59-4173-8d1d-257488dbf1b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div/div/div[8]/form/div[2]/div[2]/div[10]/div/div[4]/div[2]/div/div/div/div</value>
      <webElementGuid>d917e339-d980-44d2-ada8-d3bd398ac6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ward/Commune/Town'])[1]/following::div[5]</value>
      <webElementGuid>b30d0995-4f2c-4153-9058-d2ec5ebb8727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phú Mỹ'])[1]/following::div[7]</value>
      <webElementGuid>b608f82c-ce8c-44f7-ae99-a15d58d57022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Village/Hamlet/Residential group'])[1]/preceding::div[1]</value>
      <webElementGuid>aab281bc-73ea-4077-bdca-d9eec6a6b94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::div[6]</value>
      <webElementGuid>d120bc6b-dc49-48ec-89b0-4594bb8f3cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div</value>
      <webElementGuid>d9618acf-a98d-43b3-85ce-cb6a23a09c5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
