<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please provide the following informatio_6171eb_1</name>
   <tag></tag>
   <elementGuidId>45cecf57-f729-4f07-9a94-24b07e98f781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#credify-scrollable-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='credify-scrollable-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f07eb9ca-3b7d-4da8-82d8-d967b9178301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>credify-scrollable-content</value>
      <webElementGuid>a559b1b5-c2a2-4c20-a829-04cb40484473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bTDOke dXiuJH</value>
      <webElementGuid>c657b5b7-633a-4aed-ba27-bbdf40471847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please provide the following information in order to complete the application.Information provided by BNPL consumerOCB- ComB will securely receive these bits of information from BNPL consumerPhone numberIdentity informationBasic informationFull nameGenderMaleFemaleDay of birthMonth of birthOctoberYear of birthID numberID card date of issuanceDayMonthFebruaryYearOld ID numberEmail addressPERMANENT ADDRESSProvince/CitySelectDistrictSelectWard/Commune/TownSelectVillage/Hamlet/Residential groupAddress and permanent address are the same placesHousing typeSelectEducation levelSelectMarital statusSelectEmployment informationOccupationSelectCompany nameCompany phone numberCompany Registration typeSelectCompany IndustrySelectCOMPANY ADDRESSProvince/CitySelectDistrictSelectWard/Commune/TownSelectVillage/Hamlet/Residential groupIncome &amp; dependent personMonthly wage income20,000,000đ200,000,000đ200,000,000đNumber of dependent person-0+Reference person informationPrimary person's full nameRelationshipSelectPhone numberSecondary person's full nameRelationshipSelectspouseparentSpouseParentChildSiblingCousinColleagueNeighborFriendPhone numberWhat is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with OCB- ComB for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.</value>
      <webElementGuid>c184d061-4bae-4225-8404-08a941971bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credify-scrollable-content&quot;)</value>
      <webElementGuid>1eb0fc63-ecb9-4397-914d-9eeea0c9163f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']</value>
      <webElementGuid>91f55808-ab7c-4a65-9a69-fde22cc790e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-main-content']/div</value>
      <webElementGuid>928892bd-d1dc-4ffc-b10c-865849b1cec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[1]/following::div[5]</value>
      <webElementGuid>0ea6ec2e-3f79-4a4f-afe3-9b7b8df93e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>8f40c4ff-08e8-489e-908c-218ff10fbcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'credify-scrollable-content' and (text() = concat(&quot;Please provide the following information in order to complete the application.Information provided by BNPL consumerOCB- ComB will securely receive these bits of information from BNPL consumerPhone numberIdentity informationBasic informationFull nameGenderMaleFemaleDay of birthMonth of birthOctoberYear of birthID numberID card date of issuanceDayMonthFebruaryYearOld ID numberEmail addressPERMANENT ADDRESSProvince/CitySelectDistrictSelectWard/Commune/TownSelectVillage/Hamlet/Residential groupAddress and permanent address are the same placesHousing typeSelectEducation levelSelectMarital statusSelectEmployment informationOccupationSelectCompany nameCompany phone numberCompany Registration typeSelectCompany IndustrySelectCOMPANY ADDRESSProvince/CitySelectDistrictSelectWard/Commune/TownSelectVillage/Hamlet/Residential groupIncome &amp; dependent personMonthly wage income20,000,000đ200,000,000đ200,000,000đNumber of dependent person-0+Reference person informationPrimary person&quot; , &quot;'&quot; , &quot;s full nameRelationshipSelectPhone numberSecondary person&quot; , &quot;'&quot; , &quot;s full nameRelationshipSelectspouseparentSpouseParentChildSiblingCousinColleagueNeighborFriendPhone numberWhat is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with OCB- ComB for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.&quot;) or . = concat(&quot;Please provide the following information in order to complete the application.Information provided by BNPL consumerOCB- ComB will securely receive these bits of information from BNPL consumerPhone numberIdentity informationBasic informationFull nameGenderMaleFemaleDay of birthMonth of birthOctoberYear of birthID numberID card date of issuanceDayMonthFebruaryYearOld ID numberEmail addressPERMANENT ADDRESSProvince/CitySelectDistrictSelectWard/Commune/TownSelectVillage/Hamlet/Residential groupAddress and permanent address are the same placesHousing typeSelectEducation levelSelectMarital statusSelectEmployment informationOccupationSelectCompany nameCompany phone numberCompany Registration typeSelectCompany IndustrySelectCOMPANY ADDRESSProvince/CitySelectDistrictSelectWard/Commune/TownSelectVillage/Hamlet/Residential groupIncome &amp; dependent personMonthly wage income20,000,000đ200,000,000đ200,000,000đNumber of dependent person-0+Reference person informationPrimary person&quot; , &quot;'&quot; , &quot;s full nameRelationshipSelectPhone numberSecondary person&quot; , &quot;'&quot; , &quot;s full nameRelationshipSelectspouseparentSpouseParentChildSiblingCousinColleagueNeighborFriendPhone numberWhat is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with OCB- ComB for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.&quot;))]</value>
      <webElementGuid>849d4deb-7ac2-4ec2-b94a-1a4903a2bd90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
