<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_H NamH NiH TnhHi DngHi PhngHu GiangH Ch_a0805a</name>
   <tag></tag>
   <elementGuidId>220c0cbd-844d-4e82-b3ff-9f02608b1cb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rc-virtual-list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='----item-id----permanent_address.claims.region']/div[2]/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9cb9b305-7e9f-41e9-baa4-09c2bb525c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-virtual-list</value>
      <webElementGuid>b9e5e84f-9072-4163-8f87-23d9ec85f00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hà NamHà NộiHà TĩnhHải DươngHải PhòngHậu GiangHồ Chí MinhHòa BìnhHưng YênKhánh Hòa</value>
      <webElementGuid>b8b9b225-06c1-4452-a94c-69330a40b7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;----item-id----permanent_address.claims.region&quot;)/div[2]/div[1]/div[@class=&quot;ant-select-dropdown ant-select-dropdown-placement-bottomRight&quot;]/div[1]/div[@class=&quot;rc-virtual-list&quot;]</value>
      <webElementGuid>df166c78-f216-4b88-8d63-3cbadf7b649d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='----item-id----permanent_address.claims.region']/div[2]/div/div/div/div[2]</value>
      <webElementGuid>c883ecfc-e314-44c7-8323-119e787600c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[1]/following::div[9]</value>
      <webElementGuid>749521e9-aecd-4aca-b23c-d9a4db476698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province/City'])[1]/following::div[15]</value>
      <webElementGuid>b10bd958-0eb9-492f-b5ca-0c780d8d7f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>eb5ce14d-b431-447a-b3a0-7a5def3b6610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hà NamHà NộiHà TĩnhHải DươngHải PhòngHậu GiangHồ Chí MinhHòa BìnhHưng YênKhánh Hòa' or . = 'Hà NamHà NộiHà TĩnhHải DươngHải PhòngHậu GiangHồ Chí MinhHòa BìnhHưng YênKhánh Hòa')]</value>
      <webElementGuid>32c04f42-2465-46f7-ad27-bc0eebdfaf17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
