<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select</name>
   <tag></tag>
   <elementGuidId>3cf8f617-2a14-4a5d-b0d7-2686569b7abe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-select.ant-select-borderless.sc-kLojOw.cvTVNg.ant-select-single.ant-select-show-arrow.ant-select-open > div.ant-select-selector</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='--item-id--primary_reference_person.claims.relationship']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ea132c6-d4d9-4d51-9f57-6db3a7e43ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selector</value>
      <webElementGuid>2d58859a-2d14-465e-89f3-f16023bc60b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>902b3bad-6909-4add-9d2d-c2fc0ad35d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;--item-id--primary_reference_person.claims.relationship&quot;)/div[@class=&quot;ant-select ant-select-borderless sc-kLojOw cvTVNg ant-select-single ant-select-show-arrow ant-select-open&quot;]/div[@class=&quot;ant-select-selector&quot;]</value>
      <webElementGuid>728b441d-6fc9-4b18-a810-4f58ac930456</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='--item-id--primary_reference_person.claims.relationship']/div/div</value>
      <webElementGuid>bb4061d7-1960-48e5-90e7-6bc4cec0bc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship'])[1]/following::div[6]</value>
      <webElementGuid>08417371-3146-4db5-9aba-c29ac8dbf896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Primary person', &quot;'&quot;, 's full name')])[1]/following::div[12]</value>
      <webElementGuid>d3e7a7b9-e20b-4912-b2dd-7dfdfb02b58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='spouse'])[1]/preceding::div[1]</value>
      <webElementGuid>3f78ca4f-d932-47ee-ac4d-c765884de18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>643233e0-552a-47f6-81a2-9526c052137d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>ea6da8e3-369d-46e1-b135-bc0d5edb03fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
