<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please provide the following informatio_6171eb</name>
   <tag></tag>
   <elementGuidId>33556d1d-ce45-45b1-9008-d3b96ff6c77f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#credify-scrollable-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='credify-scrollable-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2850042-47c7-4982-9fff-e0ef66db9a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>credify-scrollable-content</value>
      <webElementGuid>5c9f2912-0014-4b84-86ce-88e70db5e311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bTDOke dXiuJH</value>
      <webElementGuid>e6ef0be9-5969-42ba-903c-97819475cf5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please provide the following information in order to complete the application.Information provided by BNPL consumerOCB- ComB will securely receive these bits of information from BNPL consumerPhone numberIdentity informationBasic informationFull nameGenderMaleFemaleDay of birthMonth of birthOctoberYear of birthID numberID card date of issuanceDayMonthFebruaryYearOld ID numberEmail addressPERMANENT ADDRESSProvince/CityHồ Chí Minh282930Hà NộiHà TĩnhHải DươngHải PhòngHậu GiangHồ Chí MinhHòa BìnhHưng YênKhánh HòaKiên GiangKon TumDistrict13113121101112234567Ward/Commune/TownBến Thành464246434644Bến NghéBến ThànhCầu KhoCầu Ông LãnhCô GiangĐa KaoNguyễn Cư TrinhNguyễn Thái BìnhPhạm Ngũ LãoTân ĐịnhVillage/Hamlet/Residential groupAddress and permanent address are the same placesHousing typeParent's houseprivate_houseparent_houserentPrivate houseParent's houseRentInstallment purchaseOtherEducation levelSecondary schoolintermediate_schoolsecondary_schoolhigh_schoolIntermediate schoolSecondary schoolHigh schoolCollegeUniversityGraduate schoolPost-gradDoctor of PhilosophyMarital statusMarriedsinglemarriedseparatedSingleMarriedSeparatedDivorcedWidowOtherSpouse informationSpouse full nameID NumberPhone numberEmployment informationOccupationFiremanpolicefiremanworkerPoliceFiremanWorkerTeacherCleanerEngineerTechnicianLawyerBrokerArtistCompany nameCompany phone numberCompany Registration typeLimitedjointlimitedstateJointLimitedStateForeignHousehold businessCooperativeCompany IndustryServiceservicefinance_insuranceServiceFinance/InsuranceReal estatePharmaceuticalAgricultureTransportGovernmentRetailConstructionEducationCOMPANY ADDRESSProvince/CityHồ Chí Minh282930Hậu GiangHồ Chí MinhHòa BìnhHưng YênKhánh HòaKiên GiangKon TumLai ChâuLâm ĐồngLạng SơnDistrict13113121101112234567Ward/Commune/TownBến Nghé46424643Bến NghéBến ThànhCầu KhoCầu Ông LãnhCô GiangĐa KaoNguyễn Cư TrinhNguyễn Thái BìnhPhạm Ngũ LãoTân ĐịnhVillage/Hamlet/Residential groupIncome &amp; dependent personMonthly wage income2,000,000đ2,000,000đ20,000,000đ200,000,000đNumber of dependent person-1+Reference person informationPrimary person's full nameRelationshipSiblingchildsiblingcousinSpouseParentChildSiblingCousinColleagueNeighborFriendPhone numberSecondary person's full nameRelationshipSpousespouseparentSpouseParentChildSiblingCousinColleagueNeighborFriendPhone numberWhat is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with OCB- ComB for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.</value>
      <webElementGuid>8494203b-999c-4d0a-b356-812906e65fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credify-scrollable-content&quot;)</value>
      <webElementGuid>fffa6956-20fe-4539-b4d0-68c5dff70423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']</value>
      <webElementGuid>48f25f86-7c8a-4df5-a8c3-f6d7be64b8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-main-content']/div</value>
      <webElementGuid>5763edd2-4cfe-49f5-9f33-4cd18b7d4cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[1]/following::div[5]</value>
      <webElementGuid>f4889802-3758-4f17-a35a-e9b58154d141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>a05fc8e1-4a6a-42f5-ab76-249e31db4d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'credify-scrollable-content' and (text() = concat(&quot;Please provide the following information in order to complete the application.Information provided by BNPL consumerOCB- ComB will securely receive these bits of information from BNPL consumerPhone numberIdentity informationBasic informationFull nameGenderMaleFemaleDay of birthMonth of birthOctoberYear of birthID numberID card date of issuanceDayMonthFebruaryYearOld ID numberEmail addressPERMANENT ADDRESSProvince/CityHồ Chí Minh282930Hà NộiHà TĩnhHải DươngHải PhòngHậu GiangHồ Chí MinhHòa BìnhHưng YênKhánh HòaKiên GiangKon TumDistrict13113121101112234567Ward/Commune/TownBến Thành464246434644Bến NghéBến ThànhCầu KhoCầu Ông LãnhCô GiangĐa KaoNguyễn Cư TrinhNguyễn Thái BìnhPhạm Ngũ LãoTân ĐịnhVillage/Hamlet/Residential groupAddress and permanent address are the same placesHousing typeParent&quot; , &quot;'&quot; , &quot;s houseprivate_houseparent_houserentPrivate houseParent&quot; , &quot;'&quot; , &quot;s houseRentInstallment purchaseOtherEducation levelSecondary schoolintermediate_schoolsecondary_schoolhigh_schoolIntermediate schoolSecondary schoolHigh schoolCollegeUniversityGraduate schoolPost-gradDoctor of PhilosophyMarital statusMarriedsinglemarriedseparatedSingleMarriedSeparatedDivorcedWidowOtherSpouse informationSpouse full nameID NumberPhone numberEmployment informationOccupationFiremanpolicefiremanworkerPoliceFiremanWorkerTeacherCleanerEngineerTechnicianLawyerBrokerArtistCompany nameCompany phone numberCompany Registration typeLimitedjointlimitedstateJointLimitedStateForeignHousehold businessCooperativeCompany IndustryServiceservicefinance_insuranceServiceFinance/InsuranceReal estatePharmaceuticalAgricultureTransportGovernmentRetailConstructionEducationCOMPANY ADDRESSProvince/CityHồ Chí Minh282930Hậu GiangHồ Chí MinhHòa BìnhHưng YênKhánh HòaKiên GiangKon TumLai ChâuLâm ĐồngLạng SơnDistrict13113121101112234567Ward/Commune/TownBến Nghé46424643Bến NghéBến ThànhCầu KhoCầu Ông LãnhCô GiangĐa KaoNguyễn Cư TrinhNguyễn Thái BìnhPhạm Ngũ LãoTân ĐịnhVillage/Hamlet/Residential groupIncome &amp; dependent personMonthly wage income2,000,000đ2,000,000đ20,000,000đ200,000,000đNumber of dependent person-1+Reference person informationPrimary person&quot; , &quot;'&quot; , &quot;s full nameRelationshipSiblingchildsiblingcousinSpouseParentChildSiblingCousinColleagueNeighborFriendPhone numberSecondary person&quot; , &quot;'&quot; , &quot;s full nameRelationshipSpousespouseparentSpouseParentChildSiblingCousinColleagueNeighborFriendPhone numberWhat is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with OCB- ComB for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.&quot;) or . = concat(&quot;Please provide the following information in order to complete the application.Information provided by BNPL consumerOCB- ComB will securely receive these bits of information from BNPL consumerPhone numberIdentity informationBasic informationFull nameGenderMaleFemaleDay of birthMonth of birthOctoberYear of birthID numberID card date of issuanceDayMonthFebruaryYearOld ID numberEmail addressPERMANENT ADDRESSProvince/CityHồ Chí Minh282930Hà NộiHà TĩnhHải DươngHải PhòngHậu GiangHồ Chí MinhHòa BìnhHưng YênKhánh HòaKiên GiangKon TumDistrict13113121101112234567Ward/Commune/TownBến Thành464246434644Bến NghéBến ThànhCầu KhoCầu Ông LãnhCô GiangĐa KaoNguyễn Cư TrinhNguyễn Thái BìnhPhạm Ngũ LãoTân ĐịnhVillage/Hamlet/Residential groupAddress and permanent address are the same placesHousing typeParent&quot; , &quot;'&quot; , &quot;s houseprivate_houseparent_houserentPrivate houseParent&quot; , &quot;'&quot; , &quot;s houseRentInstallment purchaseOtherEducation levelSecondary schoolintermediate_schoolsecondary_schoolhigh_schoolIntermediate schoolSecondary schoolHigh schoolCollegeUniversityGraduate schoolPost-gradDoctor of PhilosophyMarital statusMarriedsinglemarriedseparatedSingleMarriedSeparatedDivorcedWidowOtherSpouse informationSpouse full nameID NumberPhone numberEmployment informationOccupationFiremanpolicefiremanworkerPoliceFiremanWorkerTeacherCleanerEngineerTechnicianLawyerBrokerArtistCompany nameCompany phone numberCompany Registration typeLimitedjointlimitedstateJointLimitedStateForeignHousehold businessCooperativeCompany IndustryServiceservicefinance_insuranceServiceFinance/InsuranceReal estatePharmaceuticalAgricultureTransportGovernmentRetailConstructionEducationCOMPANY ADDRESSProvince/CityHồ Chí Minh282930Hậu GiangHồ Chí MinhHòa BìnhHưng YênKhánh HòaKiên GiangKon TumLai ChâuLâm ĐồngLạng SơnDistrict13113121101112234567Ward/Commune/TownBến Nghé46424643Bến NghéBến ThànhCầu KhoCầu Ông LãnhCô GiangĐa KaoNguyễn Cư TrinhNguyễn Thái BìnhPhạm Ngũ LãoTân ĐịnhVillage/Hamlet/Residential groupIncome &amp; dependent personMonthly wage income2,000,000đ2,000,000đ20,000,000đ200,000,000đNumber of dependent person-1+Reference person informationPrimary person&quot; , &quot;'&quot; , &quot;s full nameRelationshipSiblingchildsiblingcousinSpouseParentChildSiblingCousinColleagueNeighborFriendPhone numberSecondary person&quot; , &quot;'&quot; , &quot;s full nameRelationshipSpousespouseparentSpouseParentChildSiblingCousinColleagueNeighborFriendPhone numberWhat is this?Tired of manually input?Save all inputs with a password and reuse them next time.SaveI agree to share the information with OCB- ComB for applying for the product.If you do not agree, the application will not be made and NONE of your information will be shared.&quot;))]</value>
      <webElementGuid>6954fcbb-c024-4f03-816b-39c0d36c5905</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
