<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>d51ce38f-5393-4b10-8a24-dd0add2ea342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='credify-scrollable-content']/div/div/div[14]/form/div[2]/div/div[13]/div/div[2]/div/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a12d9feb-e53f-4fcf-825b-08e50a2eadbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fnebDD bAGyCr</value>
      <webElementGuid>d3602d97-f456-43cf-a053-e4e5b22889ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>88d037c6-4f89-474f-bff3-86ebdb74f32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credify-scrollable-content&quot;)/div[@class=&quot;sc-iJCRrE sc-giAqHp sc-hHSjgo bojiJp dHLXvA bURDyX&quot;]/div[@class=&quot;ant-col ant-col-24&quot;]/div[@class=&quot;sc-dbXCOC czOhSG&quot;]/form[@class=&quot;ant-form ant-form-vertical&quot;]/div[@class=&quot;ant-col ant-col-24 appForm-group&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-24&quot;]/div[@class=&quot;ant-row ant-form-item form--item-number_of_dependents ant-form-item-has-success&quot;]/div[@class=&quot;ant-col ant-col-24 ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;sc-dHMioH jeOpiX&quot;]/div[@class=&quot;sc-QxirK fWxumN&quot;]/div[@class=&quot;sc-fnebDD bAGyCr&quot;]</value>
      <webElementGuid>a2fb797f-d7df-49ab-86b8-c3c8e4ad5430</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div/div/div[14]/form/div[2]/div/div[13]/div/div[2]/div/div/div/div/div[2]</value>
      <webElementGuid>b85a13b7-cde7-4a2d-b1b3-63b16260d061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::div[1]</value>
      <webElementGuid>3564dd69-d282-4a6b-982f-4ab7e8e081e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of dependent person'])[1]/following::div[7]</value>
      <webElementGuid>b78d8ab4-c9b3-45c7-8e41-ce033142649a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference person information'])[1]/preceding::div[3]</value>
      <webElementGuid>750f6ab6-ad0d-43e3-80c1-4425d53a620f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Primary person', &quot;'&quot;, 's full name')])[1]/preceding::div[6]</value>
      <webElementGuid>97bc3a99-aaa1-4b3b-bc2b-fb68a5f10a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+']/parent::*</value>
      <webElementGuid>1cdf1cb0-7085-4e58-b6f7-1ed3cc420daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]/div/div/div/div/div[2]</value>
      <webElementGuid>95900a03-e57b-4b81-ad74-e2c9d3b9e1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '+' or . = '+')]</value>
      <webElementGuid>48dd2a5d-795d-4151-9c65-5a20f0b622aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
