<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Select a desired partner_serviceProvide_c6be13</name>
   <tag></tag>
   <elementGuidId>1776e810-7cee-4d70-837a-6b10287293db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#serviceProviderImage-d99f52d2-4616-11ed-95e0-86f1d5b36a93</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='serviceProviderImage-d99f52d2-4616-11ed-95e0-86f1d5b36a93']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>32f2592f-76c0-41bb-872e-1f5cd9ad67cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>serviceProviderImage</value>
      <webElementGuid>ac2ea1b3-9a02-4c7e-a313-c4e720b28f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serviceProviderImage-d99f52d2-4616-11ed-95e0-86f1d5b36a93</value>
      <webElementGuid>f2753ed0-78fa-4272-ab4d-6a3b2ec6a339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev-files.credify.ninja/e18f53c8-b683-4512-bf1a-14a7a8e4b305.png</value>
      <webElementGuid>a3915eb4-64e3-4cc0-882f-74ee1df86e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Service provider image</value>
      <webElementGuid>67923b8c-7a73-446a-a16e-1e254e011a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serviceProviderImage-d99f52d2-4616-11ed-95e0-86f1d5b36a93&quot;)</value>
      <webElementGuid>2ca87ccb-5462-4abe-94b8-dcb84d7a8fa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='serviceProviderImage-d99f52d2-4616-11ed-95e0-86f1d5b36a93']</value>
      <webElementGuid>9d203358-191f-4d76-882b-91374accefbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='serviceProviderImage-div-div-d99f52d2-4616-11ed-95e0-86f1d5b36a93']/img</value>
      <webElementGuid>17e9c630-9dcf-41a8-98d3-1d13bb4b9b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Service provider image'])[4]</value>
      <webElementGuid>ceac4f7a-3c05-45ae-8181-7dd4d5803d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/img</value>
      <webElementGuid>af9ecc40-e13d-4a95-9f93-67716d402d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'serviceProviderImage-d99f52d2-4616-11ed-95e0-86f1d5b36a93' and @src = 'https://dev-files.credify.ninja/e18f53c8-b683-4512-bf1a-14a7a8e4b305.png' and @alt = 'Service provider image']</value>
      <webElementGuid>a9aeb24e-f695-470c-b744-8219e5f26b87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
