<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_A 6-character confirmation code has verification-input-id</name>
   <tag></tag>
   <elementGuidId>2326276a-dbe0-4837-8f4f-82d370146326</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verification-input-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verification-input-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bb5644a-cef2-430a-826c-4775758fc233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4bca52aa-674e-4afc-a93d-8697c234ef20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vi</value>
      <webElementGuid>e75f545c-bb38-47f8-986f-38d15aa68244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verification-input-id</value>
      <webElementGuid>46152d9f-4497-4fbe-9e95-ee43a929258d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>a0ef0049-8c74-408e-8d6e-ff52de5f1cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>02360e07-edd2-4559-94f7-7b03c21cb167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verification-input-id&quot;)</value>
      <webElementGuid>6db203b3-e3b8-41e3-b25b-f57049c0cf96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verification-input-id']</value>
      <webElementGuid>d0680c13-2eca-4edf-9ce7-da649337ccbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div/div/div[2]/div/div/input</value>
      <webElementGuid>4e41e41f-a93f-4e2e-9494-0eb631005cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0f45c180-880d-4d86-baa0-cb86e6317a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'verification-input-id']</value>
      <webElementGuid>f2c400be-09c9-4598-a5e2-985e627bc2f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
