<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID number_idcard_number</name>
   <tag></tag>
   <elementGuidId>b0631d0c-cf83-4b1c-a3fb-e656ab081aff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idcard_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idcard_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c77f18c4-b1cd-4da1-953b-cd65db70eb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a924eca2-d0a8-4c45-94ca-2ea20b45daba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>840a034e-3422-4f86-a550-cfcd6652071f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idcard_number</value>
      <webElementGuid>ce794797-c9ec-4822-8280-2ec33c7fcbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-dIsUp krDdSx</value>
      <webElementGuid>9ef5bfa0-6be8-4552-a756-76a679e131ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>077090003241</value>
      <webElementGuid>68abb266-0692-4cd0-8e31-53023767ddb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcard_number&quot;)</value>
      <webElementGuid>80e62883-33f8-41b6-8b02-b6f866a0cfab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idcard_number']</value>
      <webElementGuid>b8a09004-568b-4827-b755-77c528f725f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div/div/div[14]/form/div/div/div[4]/div/div[2]/div/div/input</value>
      <webElementGuid>c491917b-a3ca-4747-9d41-11e2cab1477c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/input</value>
      <webElementGuid>76e1e00e-6486-42e0-9a04-333f67f519b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'idcard_number']</value>
      <webElementGuid>64831b01-77b7-4a53-99a3-82c387cfae92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
