<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VillageHamletResidential group_employ_e468ba</name>
   <tag></tag>
   <elementGuidId>ed4eba0d-8c1a-4593-ae85-ca441e0a9480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employment.claims.company_address.claims.sublocality_level_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6643feb-8c59-45bf-a0cf-4a93b592dccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employment.claims.company_address.claims.sublocality_level_2</value>
      <webElementGuid>0cad2341-948f-4a2b-a277-0c7659a04b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-dIsUp krDdSx</value>
      <webElementGuid>cde1d56e-89e0-4a74-bac4-055ed3f087e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f257cc7-0f4c-4fee-a6dc-017af3039223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employment.claims.company_address.claims.sublocality_level_2&quot;)</value>
      <webElementGuid>60da3b36-d987-46b2-a494-ff0a6cd2cd2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employment.claims.company_address.claims.sublocality_level_2']</value>
      <webElementGuid>cef772f3-83a7-4c1b-8c42-0eea0229125f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div/div/div[14]/form/div[2]/div/div[11]/div/div[5]/div[2]/div/div/input</value>
      <webElementGuid>992e3244-9795-4cc3-9f7e-726c92eb1f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[5]/div[2]/div/div/input</value>
      <webElementGuid>4b20f9ea-587e-4bf9-b551-a87bf16ccac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'employment.claims.company_address.claims.sublocality_level_2' and @type = 'text']</value>
      <webElementGuid>11f73993-aa16-4f43-b12f-61d9efb85fbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
