<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full name_primary_reference_person.cl_649161</name>
   <tag></tag>
   <elementGuidId>66ffcaba-19b8-4e63-b04f-0714e0e57d98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='primary_reference_person.claims.name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91b211d3-8923-4842-a706-bb21cfc1b408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78fa1259-2c4f-4a4b-94ca-737793e6fdcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>5ff3f4c7-4c25-49da-8c94-013cd125367a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primary_reference_person.claims.name</value>
      <webElementGuid>cccde693-185f-4276-a3bf-6703b4fbff5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-dIsUp krDdSx</value>
      <webElementGuid>34125acf-a7aa-4bda-ae27-d15b37e8fccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary_reference_person.claims.name&quot;)</value>
      <webElementGuid>79e5a3f3-2a7f-4751-91f6-b183e6b354e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='primary_reference_person.claims.name']</value>
      <webElementGuid>8e76d31e-3615-4bde-b97e-ecbfc19360d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div/div/div[8]/form/div[2]/div[2]/div[14]/div/div[2]/div/div/input</value>
      <webElementGuid>f7230b95-0c6c-4db9-95c0-e878b1dca7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div/div/input</value>
      <webElementGuid>fa137b8b-76e7-413c-ae69-b7597f0bb1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'primary_reference_person.claims.name']</value>
      <webElementGuid>da04bda9-bcd7-4932-a9eb-de20b5c81725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
