<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Monthly family income_monthly_family__6d8840</name>
   <tag></tag>
   <elementGuidId>bbf3f2b7-0bb7-4c6a-a753-a779ffa01d5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#monthly_family_income_CustomAutoComplete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='monthly_family_income_CustomAutoComplete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f73396f0-1a97-4bd9-abf4-deb8490f8ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dc117ded-3d46-4ed3-9755-08f8ad074323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monthly_family_income_CustomAutoComplete</value>
      <webElementGuid>ab1340c9-d354-4917-b100-3038be2e85bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>890667f7-a539-4b6c-a2f6-38ad0a00cde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-dIsUp krDdSx ant-select-selection-search-input</value>
      <webElementGuid>d9ddfddf-19da-489f-bd1f-8f91411f6d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>3988bc24-196c-47a5-97a9-3f134e179566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>fe5b4b8d-d315-43eb-b0b4-3fbf2043ded4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>monthly_family_income_CustomAutoComplete_list</value>
      <webElementGuid>3745e1ae-c6e6-48e9-8992-8ba05d4c0f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>8942d5e0-7c85-4c1f-bd7f-16d6df3d63d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>monthly_family_income_CustomAutoComplete_list</value>
      <webElementGuid>f0508449-807d-4377-94dd-8a36fd429a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>monthly_family_income_CustomAutoComplete_list_-1</value>
      <webElementGuid>1cf9c481-7ad6-44c6-b257-ee9aa302b6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2đ</value>
      <webElementGuid>c967e83e-84ce-4047-b3d5-f217934cbf44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>674aa062-025c-4ab4-a463-2eb2cf74d9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthly_family_income_CustomAutoComplete&quot;)</value>
      <webElementGuid>b2b61b58-86ac-493d-b912-86b3603a2cd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='monthly_family_income_CustomAutoComplete']</value>
      <webElementGuid>f309d0ef-f92e-4060-92dd-83e93106d6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div/div/div[8]/form/div[2]/div[2]/div[12]/div/div[2]/div/div/div/div/div/span/input</value>
      <webElementGuid>1166d309-273f-4c41-8baf-168749632e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[2]/div/div/div/div/div/span/input</value>
      <webElementGuid>15881285-e7a9-42b8-9911-73fc8e739252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'monthly_family_income_CustomAutoComplete' and @type = 'search']</value>
      <webElementGuid>029bce24-afb6-4136-8220-293e9c0071fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
