<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone number_primary_reference_person_d47978</name>
   <tag></tag>
   <elementGuidId>7b1d7efb-7833-48bd-8da0-d836f181ffad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='primary_reference_person.claims.phone_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3961bcde-e50e-488b-9e9e-9b40daf8839e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6c39470b-828c-4ee9-85fc-3bf93e9c0120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>3f1b1e88-a2b8-49a5-8588-7d8e7dac9b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>primary_reference_person.claims.phone_number</value>
      <webElementGuid>79380d47-4dbd-4962-ba21-255323d52f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-dIsUp krDdSx</value>
      <webElementGuid>3c8a23c3-8c62-4659-9e48-eab9860436e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary_reference_person.claims.phone_number&quot;)</value>
      <webElementGuid>b62e39fd-4de0-4409-b8ff-d971e379c662</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='primary_reference_person.claims.phone_number']</value>
      <webElementGuid>ab3e31cc-846a-41be-8a21-cfec30275f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div/div/div[14]/form/div[2]/div/div[16]/div/div[2]/div/div/input</value>
      <webElementGuid>ef32df3b-636c-435a-914d-05877249921a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div[2]/div/div/input</value>
      <webElementGuid>fca046bf-7be3-4124-b729-90a041d9724c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'primary_reference_person.claims.phone_number']</value>
      <webElementGuid>fc053ffa-74e5-44aa-9b83-0e714e424133</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
