<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Monthly wage income_monthly_wage_inco_d5d4bc</name>
   <tag></tag>
   <elementGuidId>65e0a326-8fb8-40c4-aed0-a30fc4af874d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#monthly_wage_income_CustomAutoComplete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='monthly_wage_income_CustomAutoComplete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa43f647-fd18-41e4-a812-06fa87f278d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>11f77b20-da75-4d86-ae69-10df2f238f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monthly_wage_income_CustomAutoComplete</value>
      <webElementGuid>c2d3c8d1-0c56-4519-af84-c8843eb7e052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>9ab2f6a7-47e3-4c51-8f53-2e748c5468ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-dIsUp krDdSx ant-select-selection-search-input</value>
      <webElementGuid>6665dcc3-1659-4e81-86a0-7b8abb53a441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>6e9b02f5-8082-4daa-b151-d2de205e4f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>55df4930-bc24-446a-9235-d60842ade04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>monthly_wage_income_CustomAutoComplete_list</value>
      <webElementGuid>08795b11-17ad-4e55-9d26-5b9df85cf4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>297c297c-bc45-4ca5-9177-349275472df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>monthly_wage_income_CustomAutoComplete_list</value>
      <webElementGuid>97b36a4f-7796-420d-a24b-1aa79d7a0e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>monthly_wage_income_CustomAutoComplete_list_-1</value>
      <webElementGuid>ef9f1a43-6394-4cf2-8eb2-6199d49b1572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2đ</value>
      <webElementGuid>41621f5e-3382-4a67-849c-055de86deec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c7333612-ed41-49e9-a46c-9e020c87bf4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthly_wage_income_CustomAutoComplete&quot;)</value>
      <webElementGuid>082233e2-7e34-4091-90c4-b40dca3ba936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='monthly_wage_income_CustomAutoComplete']</value>
      <webElementGuid>9647c35d-461a-4d4b-bb60-85bcc2af89ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div/div/div[14]/form/div[2]/div/div[12]/div[2]/div[2]/div/div/div/div/div/span/input</value>
      <webElementGuid>e0e0f836-0cd5-4bfc-93e4-df32b75db7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/div[2]/div/div/div/div/div/span/input</value>
      <webElementGuid>20adf163-0594-476d-b8c5-c9140e32b388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'monthly_wage_income_CustomAutoComplete' and @type = 'search']</value>
      <webElementGuid>4485e128-2054-493f-ae11-3bb37290982c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
