<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Old ID number_idcard_old_number</name>
   <tag></tag>
   <elementGuidId>bc40f92d-3aba-4844-80b5-ddf29875d08f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idcard_old_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idcard_old_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85c3c4c5-9ffd-433b-a392-226b7012be75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff5d3dfd-a617-46f2-ac87-9d5ea00e88c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>a3b325f7-ef56-4bee-9cc3-5c965368745b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idcard_old_number</value>
      <webElementGuid>ad567704-9116-42e6-9e43-d04f5ecfaa74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-dIsUp krDdSx</value>
      <webElementGuid>48425977-81b6-4b0f-83dd-24986c1578cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcard_old_number&quot;)</value>
      <webElementGuid>2e4f95fe-9a23-4ae5-b60c-5421ed00766f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idcard_old_number']</value>
      <webElementGuid>69a49f10-aad3-4a50-ab1b-40418a7c3a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div/div/div[14]/form/div/div/div[6]/div/div[2]/div/div/input</value>
      <webElementGuid>3cfe7f9f-b8c6-4e2e-aaf8-264e6a63db0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/input</value>
      <webElementGuid>fa251c1c-3c68-477e-be91-cde77837d71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'idcard_old_number']</value>
      <webElementGuid>dfd658e8-1e64-41dd-953d-45d28a85238f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
