<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street number_employment.claims.work__207850</name>
   <tag></tag>
   <elementGuidId>efa9f5b5-f34b-495e-b763-55298513f4d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employment.claims.work_address.claims.street_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>114ad568-b7d0-460e-944c-8b6c39a228b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employment.claims.work_address.claims.street_number</value>
      <webElementGuid>e481e518-ea97-4132-ae93-6444a5dddd75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-dIsUp krDdSx</value>
      <webElementGuid>79aa5eb9-f294-4fb0-a9b6-aacb4fb789ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>565e5f03-bb0d-4648-8d38-74725ff819f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employment.claims.work_address.claims.street_number&quot;)</value>
      <webElementGuid>e6da0ed9-a407-4a4b-ab50-db5f99bba7c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employment.claims.work_address.claims.street_number']</value>
      <webElementGuid>6ddfa470-52fd-4613-a8e7-f29a52216623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div/div/div[8]/form/div[2]/div[2]/div[10]/div/div[8]/div[2]/div/div/input</value>
      <webElementGuid>04e6c7ca-47b6-4f8e-8fc3-2ff2bf658329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div/input</value>
      <webElementGuid>23ea4617-ee9e-4663-b981-f1df74fff327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'employment.claims.work_address.claims.street_number' and @type = 'text']</value>
      <webElementGuid>a1aca872-4000-4a33-95ff-2ebc0485a875</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
