<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID Number_spouse.claims.idcard_number</name>
   <tag></tag>
   <elementGuidId>883f6964-939b-4fc3-9005-0f0af66d3f32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='spouse.claims.idcard_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cb7208b-5df2-43b0-a9f3-31619c33fc34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>string</value>
      <webElementGuid>71322a51-0a15-44a4-aae5-5ff7055c2129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>7e68ee73-e7d4-4c9e-8212-22ac400670b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spouse.claims.idcard_number</value>
      <webElementGuid>edb872db-2ff8-42dd-9d01-066b8c139444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input sc-dIsUp krDdSx</value>
      <webElementGuid>98727015-02e7-4a8b-8c41-89dab505fcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spouse.claims.idcard_number&quot;)</value>
      <webElementGuid>fdf786a1-1580-4a3c-bc23-9f1e35b12673</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='spouse.claims.idcard_number']</value>
      <webElementGuid>2ccd808e-c058-47d1-a622-8af3f0835554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div/div/div[14]/form/div[2]/div/div[7]/div/div[2]/div/div/input</value>
      <webElementGuid>d8716a8a-05e4-48f2-838a-659e007f30de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[7]/div/div[2]/div/div/input</value>
      <webElementGuid>f9827cbd-1bc0-4440-9540-67e86cc47408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'string' and @id = 'spouse.claims.idcard_number']</value>
      <webElementGuid>fea58609-7fef-483d-a4f3-6d96caee6614</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
