<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_A 6-character confirmation code has b_6f3212</name>
   <tag></tag>
   <elementGuidId>5e381713-15be-45fc-bb44-c16ad3fe375c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verification-input-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verification-input-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c395c431-89fc-4b5b-8aa5-b4c1be5e0e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0357c5b7-f2a5-4390-861e-1c851a49038a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vi</value>
      <webElementGuid>586bb940-f73f-47aa-920e-b7fcf55a7185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verification-input-id</value>
      <webElementGuid>e5594ba8-1f0a-4913-bf19-fbda842442a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>ffe2baa3-bc1a-4a15-8043-9d36b6fe721e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verification-input-id&quot;)</value>
      <webElementGuid>470d4137-2720-4019-9373-8cce4a522e4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verification-input-id']</value>
      <webElementGuid>c915acbc-3900-4cbd-b619-8c3818419e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credify-scrollable-content']/div/div/div[2]/div/div/input</value>
      <webElementGuid>327db5e0-b9d0-48e2-a80b-26dbd122ce11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>901a3165-7468-46de-9fbd-1122a7d528e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'verification-input-id']</value>
      <webElementGuid>9418d106-e1d3-4ba2-bf67-8b759ec6842d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
